apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: test
  region: us-east-1

managedNodeGroups:
  - name: worker
    instanceType: c7i-flex.large
    desiredCapacity: 2
    spot: true